repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
            - id: check-added-large-files
            - id: trailing-whitespace
            - id: check-docstring-first

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v0.770"
      hooks:
            - id: mypy
              args: [--config-file, pyproject.toml]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.2
      hooks:
            - id: flake8
    - repo: https://github.com/pre-commit/mirrors-yapf
      rev: "v0.30.0"
      hooks:
            - id: yapf
    - repo: https://github.com/myint/unify
      rev: v0.5
      hooks:
            - id: unify
              args: [--in-place, --recursive ]
    - repo: local
      hooks:
        - id: tests
          name: run tests
          entry: python -m unittest discover
          language: python
          types: [python]
          pass_filenames: false

        #   stages: [commit]
